# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# Default configuration for use with tic package
# Usually you shouldn't need to change the first part of the file

# DO NOT CHANGE THE CODE BELOW

stages:
- prepare
- test
- name: deploy
  if: branch = master

jobs:
  include:
  - stage: prepare
    script:
    - R -q -e 'install.packages("remotes"); remotes::install_local(getwd()); tic::prepare_all_stages(); tic::before_install()'
  - stage: test
    script:
    - R -q -e 'tic::install()'
    - R -q -e 'tic::after_install()'
    - R -q -e 'tic::before_script()'
    - R -q -e 'tic::script()'
  - stage: deploy
    script:
    - R -q -e 'tic::before_deploy()'
    - R -q -e 'tic::deploy()'
    - R -q -e 'tic::after_deploy()'

after_success: R -q -e 'tic::after_success()'
after_failure: R -q -e 'tic::after_failure()'
after_script: R -q -e 'tic::after_script()'
# DO NOT CHANGE THE CODE ABOVE

# Custom parts:

# Header
language: r
sudo: false
dist: trusty
cache: packages
latex: false

#env
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"

#matrix: 3x Linux, 1x OS X
matrix:
  include:
  - r: release
    env:
    - BUILD_PKGDOWN=true
  - r: oldrel
  - r: devel
  - os: osx
    osx_image: xcode7.3
    r: release
    latex: false

#services
services:
